const ACTION_TYPE = {
	SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
	SIGNUP_FAIL: 'SIGNUP_FAIL',
	LOGIN_SUCCESS: 'LOGIN_SUCCESS',
	LOGIN_FAIL: 'LOGIN_FAIL',
	LOADING: 'LOADING',
	CREATE_RIDE_SUCCESS: 'CREATE_RIDE_SUCCESS',
	CREATE_RIDE_FAIL: 'CREATE_RIDE_FAIL'
};
export default ACTION_TYPE;
